{
 "title": "Node Exporter / Node Filesystem and Disk Custom",
 "tags": [ "linux-node-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info{sysname!=\"Darwin\", job=\"integrations/node_exporter\", }, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(node_uname_info{job=\"integrations/node_exporter\", job=~\"$job\",}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Space Available",
   "type": "timeseries",
   "description": "Filesystem space utilisation in bytes, by mountpoint.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "description": "Disk utilisation in percent, by mountpoint. Some duplication can occur if the same filesystem is mounted in multiple locations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Free inodes",
   "type": "timeseries",
   "description": "The inode is a data structure in a Unix-style file system that describes a file-system object such as a file or a directory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    },
    {
     "expr": "node_filesystem_files{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Total inodes",
   "type": "timeseries",
   "description": "The inode is a data structure in a Unix-style file system that describes a file-system object such as a file or a directory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Filesystems with errors / read-only",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    },
    {
     "expr": "node_filesystem_device_error{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "description": "File descriptor is a handle to an open file or input/output (I/O) resource, such as a network socket or a pipe.\nThe operating system uses file descriptors to keep track of open files and I/O resources, and provides a way for programs to read from and write to them.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=~\"$job\",instance=~\"$instance\"} or node_filefd_maximum{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{job=~\"$job\",instance=~\"$instance\"} or node_filefd_allocated{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk read/writes in bytes, and total IO seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk IOps completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} writes completed"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])\n/\nirate(node_disk_reads_completed_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])\n",
     "legendFormat": "{{device}} read wait time avg"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])\n/\nirate(node_disk_writes_completed_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])\n",
     "legendFormat": "{{device}} write wait time avg"
    }
   ]
  },
  {
   "title": "Average Queue Size (aqu-sz)",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}